# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-23 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('locked_out', models.BooleanField()),
                ('last_seen', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='Everything')),
                ('points', models.IntegerField()),
                ('content', models.TextField()),
                ('answer', models.TextField()),
                ('duration', models.FloatField()),
                ('difficulty', models.TextField(default='HS')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('state', models.CharField(choices=[('idle', 'idle'), ('playing', 'playing'), ('contest', 'contest')], default='idle', max_length=9)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=1)),
                ('buzz_start_time', models.FloatField(default=0)),
                ('buzz_end_time', models.FloatField(default=1)),
                ('category', models.CharField(choices=[('Everything', 'Everything'), ('Science', 'Science'), ('History', 'History'), ('Literature', 'Literature'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Geography', 'Geography'), ('Fine Arts', 'Fine Arts'), ('Social Science', 'Social Science'), ('Mythology', 'Mythology'), ('Trash', 'Trash')], default='Everything', max_length=30)),
                ('difficulty', models.CharField(choices=[('College', 'College'), ('MS', 'MS'), ('HS', 'HS')], default='HS', max_length=10)),
                ('buzz_player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buzz_player', to='game.Player')),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game.Question')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.Room'),
        ),
    ]
