# Generated by Django 2.2.7 on 2020-05-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200524_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='tag',
            field=models.CharField(choices=[('join', 'join'), ('leave', 'leave'), ('buzz_init', 'buzz_init'), ('buzz_correct', 'buzz_correct'), ('buzz_wrong', 'buzz_wrong'), ('set_category', 'set_category'), ('set_difficulty', 'set_difficulty'), ('reset_score', 'reset_score'), ('chat', 'chat')], max_length=20),
        ),
    ]
