# Generated by Django 2.2.7 on 2020-05-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200524_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='negs',
            field=models.IntegerField(default=0),
        ),
    ]
