# Generated by Django 2.2.7 on 2020-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
    ]
