# Generated by Django 2.2.7 on 2020-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_player_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='muted',
            field=models.ManyToManyField(to='game.Player'),
        ),
    ]
