# Generated by Django 2.2.7 on 2020-05-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200528_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='muted',
        ),
    ]
