version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker-compose containers
          command: docker-compose build
      - run:
          name: Test containers
          command: docker-compose run --rm web pytest