# Generated by Django 2.0.6 on 2018-11-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('points', models.IntegerField()),
                ('content', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('idle', 'idle'), ('playing', 'playing'), ('contest', 'contest')], default='idle', max_length=9)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
                ('locked_out_players', models.ManyToManyField(blank=True, related_name='locked_out_players', to='game.Player')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='game.Player')),
            ],
        ),
    ]
