# Generated by Django 2.2.7 on 2020-05-29 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('negs', models.IntegerField(default=0)),
                ('locked_out', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('last_seen', models.FloatField(default=0)),
                ('reported_by', models.ManyToManyField(to='game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(default='Everything')),
                ('points', models.IntegerField()),
                ('content', models.TextField()),
                ('answer', models.TextField()),
                ('duration', models.FloatField()),
                ('difficulty', models.TextField(default='HS')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('state', models.CharField(choices=[('idle', 'idle'), ('playing', 'playing'), ('contest', 'contest')], default='idle', max_length=9)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=1)),
                ('buzz_start_time', models.FloatField(default=0)),
                ('buzz_end_time', models.FloatField(default=1)),
                ('category', models.CharField(choices=[('Everything', 'Everything'), ('Science', 'Science'), ('History', 'History'), ('Literature', 'Literature'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Geography', 'Geography'), ('Fine Arts', 'Fine Arts'), ('Social Science', 'Social Science'), ('Mythology', 'Mythology'), ('Trash', 'Trash')], default='Everything', max_length=30)),
                ('difficulty', models.CharField(choices=[('College', 'College'), ('MS', 'MS'), ('HS', 'HS')], default='HS', max_length=10)),
                ('buzz_player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buzz_player', to='game.Player')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='game.Question')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.CharField(choices=[('join', 'join'), ('leave', 'leave'), ('buzz_init', 'buzz_init'), ('buzz_correct', 'buzz_correct'), ('buzz_wrong', 'buzz_wrong'), ('buzz_forfeit', 'buzz_forfeit'), ('set_category', 'set_category'), ('set_difficulty', 'set_difficulty'), ('reset_score', 'reset_score'), ('chat', 'chat')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.Player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.Room')),
            ],
        ),
    ]
