# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('locked_out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('points', models.IntegerField()),
                ('content', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('state', models.CharField(choices=[('idle', 'idle'), ('playing', 'playing'), ('contest', 'contest')], default='idle', max_length=9)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.Room'),
        ),
    ]
