# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
