# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181114_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
    ]
