# Generated by Django 2.2.7 on 2020-05-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_message_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='change_locked',
            field=models.BooleanField(default=False),
        ),
    ]
