# Generated by Django 2.0.6 on 2018-11-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181114_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
    ]
