# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181115_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1542311483.201095),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1542311483.201095),
        ),
    ]
