# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181115_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1542312349.125558),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1542312348.125558),
        ),
    ]
