# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181115_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='buzz_end_time',
            field=models.FloatField(default=1542314146.100963),
        ),
        migrations.AddField(
            model_name='room',
            name='buzz_player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buzz_player', to='game.Player'),
        ),
        migrations.AddField(
            model_name='room',
            name='buzz_start_time',
            field=models.FloatField(default=1542314145.100963),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1542314146.100963),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1542314145.100963),
        ),
    ]
