# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20181117_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='player',
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_end_time',
            field=models.FloatField(default=1542545024.589503),
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_start_time',
            field=models.FloatField(default=1542545023.589503),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1542545024.589503),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1542545023.589503),
        ),
    ]
