# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20181123_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen',
            field=models.FloatField(default=1543022816.203678),
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_end_time',
            field=models.FloatField(default=1543022817.202681),
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_start_time',
            field=models.FloatField(default=1543022816.202681),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1543022817.202681),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1543022816.202681),
        ),
    ]
