# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-24 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20181123_2029'),
        ('game', '0002_auto_20181123_2029'),
    ]

    operations = [
    ]
