# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-24 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20181123_2031'),
        ('game', '0002_auto_20181123_2035'),
        ('game', '0004_auto_20181123_2033'),
    ]

    operations = [
    ]
