# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_merge_20181123_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen',
            field=models.FloatField(default=1543023513.624033),
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_end_time',
            field=models.FloatField(default=1543023514.623043),
        ),
        migrations.AlterField(
            model_name='room',
            name='buzz_start_time',
            field=models.FloatField(default=1543023513.623043),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.FloatField(default=1543023514.622039),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.FloatField(default=1543023513.622039),
        ),
    ]
