name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEBUG: "True"
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - uses: astral-sh/setup-uv@v5
      - run: uv run manage.py migrate
      - run: uv run manage.py loaddata fixtures/default_rooms.json
      - run: uv run manage.py loaddata fixtures/sample.json
      - run: uv run pytest